Сложность игры
maries-you/tetris pull request #38
Opened 2023-05-29 16:34 UTC by HolikAliaksandr

Реализована сложность игры + вариант рестарта игры

2023-05-29 16:35 UTC, HolikAliaksandr commented
Я как тестировщик пока не заучил как там мержить изменения) простите за неудобства

2023-05-29 17:37 UTC, thehighestmath commented
https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode
Очень важно нажать

2023-05-29 17:39 UTC, thehighestmath commented
> Я как тестировщик пока не заучил как там мержить изменения) простите за неудобства

Мерджить тебе и не нужно)

2023-05-29 17:43 UTC, thehighestmath commented
Кажется, что сложность можно менять в рантайме. А надо бы только 1 раз её установить в начале игры и играть

2023-05-29 19:16 UTC, thehighestmath requested changes

2023-05-29 19:16 UTC, thehighestmath commented on game.html
> +                    </br></br></br></br><p></p>
тег `<br>` одинарный
надо `<br>` а не `</br>`

2023-05-29 19:16 UTC, thehighestmath commented on game.html
> +					<button id="plusLevel">+ к сложности</button><p> Сложность игры: &nbsp <output id="levelGame" value="1">1</output></p><button id="minusLevel">- к скорости игры </button>
Добавить переносов строк

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +    return arr;
`return` не нужен

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +function getArray() {
`updateExsistingBlocks`

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +        levelObject.level = levelObject.level + 1;
`levelObject.level++;`

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +        levelObject.level = levelObject.level - 1;
`levelObject.level--;`

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +function getInsexForLevel() {
typo
`getIndexForLevel`

мб функция станет не нужна

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +        case (2):
скобки не нужны
`case 2`

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +const levelObject = { level: 1, index: 19 };
убрать индекс
1 уровень == генерация только 1-ой строки из кубиков

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +    if (levelObject.level < 4) {
ограничение должно быть `MAX_HEIGHT / SQUARE_SIZE`

2023-05-29 19:16 UTC, thehighestmath commented on game.js
> +        document.querySelector('#levelGame').innerHTML = levelObject.level;
вынести дублирующийся код в отдельную функцию

2023-05-30 11:05 UTC, HolikAliaksandr commented on game.js
> +function getInsexForLevel() {
stringSetLevel. - номер строки, с которой начинается надстройка доп сложности.

2023-05-30 11:05 UTC, HolikAliaksandr commented on game.js
> +function getArray() {
убрал

2023-05-30 11:12 UTC, HolikAliaksandr commented on game.js
> +const levelObject = { level: 1, index: 19 };
сделал

2023-05-30 11:12 UTC, HolikAliaksandr commented on game.js
> +    return arr;
убрал

2023-05-30 11:12 UTC, HolikAliaksandr commented on game.js
> +    if (levelObject.level < 4) {
есть

2023-05-30 13:25 UTC, thehighestmath requested changes

2023-05-30 13:25 UTC, thehighestmath commented on game.js
> +function getArray() {
Тут надо было переименовать функцию. Не поправлено

2023-05-30 13:25 UTC, thehighestmath commented on game.js
> +function addGameLevelFunction() {
Function лишнее слово в названии функции, ведь у нас есть ключевое слово  function

2023-05-30 13:25 UTC, thehighestmath commented on game.js
> +            };
А тут точно нужна точка с запятой?

2023-05-30 13:25 UTC, thehighestmath commented on game.js
> +        };
Точка с запятой?

2023-05-30 13:25 UTC, thehighestmath commented on game.js
> +    setInterval(deleteRow, 100);
Это плохой дизайн. Теперь у нас 2 глобальных цикла
Игровой, где фигура спускается
И второй, который проверяет надо ли удалить строку, это лишняя нагрузка на процессор. Давай это вернём как было

2023-05-30 13:25 UTC, thehighestmath commented on game.js
> +    setInterval(deleteRow, 100);
Плюс этот цикл не удается при смене скорости, т.е. будет в какой-то момент несколько циклов на удаление строки

2023-05-30 13:25 UTC, thehighestmath commented on game.js
> +y = -SQUARE_SIZE * heightFigure();
Тут комментарий про то, что нет пустой строки в конце файла

2023-05-30 13:30 UTC, HolikAliaksandr commented on game.js
> +    setInterval(deleteRow, 100);
Но! Это устраняет дефект. Теперь если держать зажатой кнопку "вниз" до удаления ряда новая фигура не выстрелит.

2023-05-30 13:31 UTC, HolikAliaksandr commented on game.js
> +y = -SQUARE_SIZE * heightFigure();
А нужна эта пустая строка в конце файла?

2023-05-30 14:19 UTC, thehighestmath commented on game.js
> +let stringSetLevel = 19;
А откуда 19?
Разве это не `MAX_HEIGHT / SQUARE_SIZE`?

2023-05-30 14:20 UTC, thehighestmath commented on game.js
> +y = -SQUARE_SIZE * heightFigure();
Да, нужна
1. линтер ругается
2. так лучше будет потом

2023-05-30 15:03 UTC, HolikAliaksandr commented on game.js
> +function getArray() {
Поправил.

2023-05-30 15:06 UTC, HolikAliaksandr commented on game.js
> +function addGameLevelFunction() {
Переименовал.

2023-05-30 15:16 UTC, HolikAliaksandr commented on game.js
> +    setInterval(deleteRow, 100);
Я немного переделал. Вынес отдельно удаление строки. Пробовал с таймаутом 300 мс - маловато. Успевает порой фигура свалится до удаления ряда. Но вообще есть идея как это все от таймера отвязать - но там кода будет больше! С учетом сложности проекта - пока можно так оставить.

2023-05-30 16:35 UTC, thehighestmath commented on game.js
> +let stringSetLevel = 19;
Ну я понимаю, что -1 надо) А скобки зачем?) Деление же выполнится раньше вычитания))

2023-05-30 16:36 UTC, HolikAliaksandr commented on game.js
> +let stringSetLevel = 19;
Перестраховался. Вспомнил анекдот про 1+1 = 11))

2023-05-30 16:54 UTC, thehighestmath approved these changes

2023-05-30 16:55 UTC, merged