Reset game
maries-you/tetris pull request #57
Opened 2023-06-13 20:48 UTC by HolikAliaksandr

2023-06-13 20:59 UTC, thehighestmath requested changes

2023-06-13 20:59 UTC, thehighestmath commented on game.js
> +    }
1. это можно сделать проще
```javascript
pause = false;
```

2. зачем `return`? где-то используется возвращаемое значение?

2023-06-13 20:59 UTC, thehighestmath commented on game.js
> +    y = -(SQUARE_SIZE*3);
1. почему 3?
2. пробелы вокруг оператора `*`

2023-06-14 07:46 UTC, HolikAliaksandr commented on game.js
> +let x = SQUARE_SIZE*3;
Это смещение к центру. В этой строке задано положение первой фигуры в игре, в 465 - следующих появившихся фигур.

2023-06-14 08:36 UTC, thehighestmath requested changes

2023-06-14 08:36 UTC, thehighestmath commented on game.js
> +let x = SQUARE_SIZE * 3;
Не поправил

2023-06-14 09:13 UTC, thehighestmath approved these changes

2023-06-14 09:14 UTC, merged