Dark theme
maries-you/tetris pull request #88
Opened 2023-06-23 18:17 UTC by wendyclear3

2023-06-23 18:31 UTC, thehighestmath requested changes

2023-06-23 18:31 UTC, thehighestmath commented on frontend/js/game.js
> +    if (!dark) {
Зачем инверсия?
Можно же просто if dark и условия поменять местами

2023-06-23 18:31 UTC, thehighestmath commented on img/tetris.jpg
Это файл уже есть в репозитории

2023-06-23 18:31 UTC, thehighestmath commented on frontend/css/game.css
> +    background-image: url(../img/tetris.jpg);
Наверное эта строка не нуждалась в замене

2023-06-23 19:18 UTC, wendyclear3 commented on frontend/css/game.css
> +    background-image: url(../img/tetris.jpg);
Это нужно для того, чтобы изображение поставить на место

2023-06-23 19:34 UTC, wendyclear3 commented on frontend/css/game.css
> +    background-image: url(../img/tetris.jpg);
ващееее) когда запускала, изображения не было, так как папка с пикчами находилась выше уровнем)

2023-06-23 19:47 UTC, thehighestmath commented on frontend/css/game.css
> +    background-image: url(../img/tetris.jpg);
а это?)

2023-06-23 19:50 UTC, thehighestmath requested changes

2023-06-23 19:50 UTC, thehighestmath commented on frontend/css/game.css
> +    background-image: url(/img/tetris.jpg);
слеш остался

2023-06-24 04:39 UTC, thehighestmath approved these changes

2023-06-24 04:40 UTC, merged